# ===== Server =====
server.port=8080

# ===== PostgreSQL Database =====
spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:31354/railway
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=0X0hiuqdINQymOLKZRFtteXUgHVBzAkJ

# ===== JPA =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== App Name =====
spring.application.name=student-management